function configQuad1 QuadMenu =
(
	QuadMenu.setTitle("M A T E R I A L 1")

	QuadMenu.addMenu("_Material-Edit")

)

function configQuad2 QuadMenu =
(
	QuadMenu.setTitle("M A T E R I A L 2")

	QuadMenu.addMenu("_Material-Selection")
)

function configQuad3 QuadMenu =
(
	QuadMenu.setTitle("M A T E R I A L 3")

	QuadMenu.addMenu("_Material-ID")
)

function configQuad4 QuadMenu =
(
	QuadMenu.setTitle("M A T E R I A L 4")

	QuadMenu.addMenu("_Material-Types")
)
